// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"gorm.io/gorm"
	"gosuper/app/http/controllers"
	"gosuper/app/repositories"
	"gosuper/app/services"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) *App {
	app := NewApp(db)
	return app
}

func InitializeUserRepository(db *gorm.DB) *repositories.UserRepository {
	userRepository := repositories.NewUserRepository(db)
	return userRepository
}

func InitializeUserService(db *gorm.DB) *services.UserService {
	userRepository := InitializeUserRepository(db)
	userService := services.NewUserService(userRepository)
	return userService
}

func InitializeAuthService(db *gorm.DB) *services.AuthService {
	userService := InitializeUserService(db)
	authService := services.NewAuthService(userService)
	return authService
}

func InitializeAuthController(authService *services.AuthService) *controllers.AuthController {
	authController := controllers.NewAuthController(authService)
	return authController
}

func InitializeUserController(userService *services.UserService) *controllers.UserController {
	userController := controllers.NewUserController(userService)
	return userController
}
